---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - gemfiles/**/*
    - vendor/**/*

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
