rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rspec
gemfile:
  - Gemfile
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
