# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple_auth}
  s.version = "1.0.2.beta.2"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira"]
  s.date = %q{2010-10-12}
  s.description = %q{When Authlogic & Devise are just too much.}
  s.email = %q{fnando.vieira@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     ".rspec",
     "Gemfile",
     "Gemfile.lock",
     "README.markdown",
     "Rakefile",
     "config/locales/en.yml",
     "config/locales/pt.yml",
     "lib/simple_auth.rb",
     "lib/simple_auth/action_controller.rb",
     "lib/simple_auth/active_record.rb",
     "lib/simple_auth/config.rb",
     "lib/simple_auth/generator.rb",
     "lib/simple_auth/helper.rb",
     "lib/simple_auth/railtie.rb",
     "lib/simple_auth/session.rb",
     "lib/simple_auth/version.rb",
     "simple_auth.gemspec",
     "spec/controllers/redirect_logged_user_spec.rb",
     "spec/controllers/require_logged_user_spec.rb",
     "spec/schema.rb",
     "spec/simple_auth/active_record_spec.rb",
     "spec/simple_auth/config_spec.rb",
     "spec/simple_auth/helper_spec.rb",
     "spec/simple_auth/session_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/app/controllers/application_controller.rb",
     "spec/support/app/models/account.rb",
     "spec/support/app/models/user.rb",
     "spec/support/app/views/dashboard/index.erb",
     "spec/support/app/views/session/new.erb",
     "spec/support/config/boot.rb",
     "spec/support/config/database.yml",
     "spec/support/config/routes.rb",
     "templates/initializer.rb"
  ]
  s.homepage = %q{http://github.com/fnando/simple_auth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple authentication system for Rails apps}
  s.test_files = [
    "spec/controllers/redirect_logged_user_spec.rb",
     "spec/controllers/require_logged_user_spec.rb",
     "spec/schema.rb",
     "spec/simple_auth/active_record_spec.rb",
     "spec/simple_auth/config_spec.rb",
     "spec/simple_auth/helper_spec.rb",
     "spec/simple_auth/session_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/app/controllers/application_controller.rb",
     "spec/support/app/models/account.rb",
     "spec/support/app/models/user.rb",
     "spec/support/config/boot.rb",
     "spec/support/config/routes.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
  end
end

